---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: demo
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:EugeneAikashev/flux-helm-poc.git
    path: charts/podinfo
    ref: master
  valuesFrom:
  - configMapKeyRef:
      name: podinfo
      namespace: demo
      key: values.yaml
      optional: false
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 3.1.5
    replicaCount: 2
    ui:
#      message: "Message from HelmRelease! Test 1"
      color: "green"
  
 
   
